[book]
authors = ["Jacob Homanics"]
language = "en"
multilingual = false
src = "src"
title = "Reputation & Roles Book"

[output.html]
git-repository-url = "https://github.com/Hotmanics/rep-and-roles-docs"
